server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: unie26
    password: 1234
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health


